import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import TransicionEscalera from "@/components/TransicionEscalera";
import Footer from "@/components/Footer";
import ChatAgent from "@/components/ChatAgent";

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "800", "900"],
});



export const metadata = {
  title: "Diseño Web En Valencia | LCastCode",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${robotoCondensed.variable}`}
      >
        <Header />
        <TransicionEscalera />
        <PageTransition>
          {children}
        </PageTransition>
        <Footer />
        <ChatAgent />
      </body>
    </html>
  );
}
